const distributionsInfoDiscrete = {
    bernoulli: {
        type: "discrete",
        name: "Bernoulli",
        id: "bernoulli",
        parametersNames: ["p"],
        parametersValues: [0.7],
        numberParameters: 1,
    },
    binomial: {
        type: "discrete",
        name: "Binomial",
        id: "binomial",
        parametersNames: ["n", "p"],
        parametersValues: [50, 0.2],
        numberParameters: 2,
    },
    geometric: {
        type: "discrete",
        name: "Geometric",
        id: "geometric",
        parametersNames: ["p"],
        parametersValues: [0.3],
        numberParameters: 1,
    },
    hypergeometric: {
        type: "discrete",
        name: "Hypergeometric",
        id: "hypergeometric",
        parametersNames: ["N", "K", "p"],
        parametersValues: [200, 50, 70],
        numberParameters: 3,
    },
    logarithmic: {
        type: "discrete",
        name: "Logarithmic",
        id: "logarithmic",
        parametersNames: ["p"],
        parametersValues: [0.8],
        numberParameters: 1,
    },
    negative_binomial: {
        type: "discrete",
        name: "Negative Binomial",
        id: "negative_binomial",
        parametersNames: ["r", "p"],
        parametersValues: [30, 0.8],
        numberParameters: 2,
    },
    poisson: {
        type: "discrete",
        name: "Poisson",
        id: "poisson",
        parametersNames: ["lambda"],
        parametersValues: [8],
        numberParameters: 1,
    },
    uniform: {
        type: "discrete",
        name: "Uniform",
        id: "uniform",
        parametersNames: ["min", "max"],
        parametersValues: [20, 50],
        numberParameters: 2,
    },
};