const distributionsInfoContinious = {
    alpha: {
        type: "continious",
        name: "Alpha",
        id: "alpha",
        parametersNames: ["alpha", "loc", "scale"],
        parametersValues: [10, 100, 3],
        numberParameters: 3,
    },
    arcsine: {
        type: "continious",
        name: "Arcasine",
        id: "arcsine",
        parametersNames: ["a", "b"],
        parametersValues: [10, 100],
        numberParameters: 2,
    },
    argus: {
        type: "continious",
        name: "Argus",
        id: "argus",
        parametersNames: ["chi", "loc", "scale"],
        parametersValues: [0.7, 100, 200],
        numberParameters: 3,
    },
    beta: {
        type: "continious",
        name: "Beta",
        id: "beta",
        parametersNames: ["alpha", "beta", "A", "B"],
        parametersValues: [10, 8, 20, 30],
        numberParameters: 4,
    },
    beta_prime: {
        type: "continious",
        name: "Beta Prime",
        id: "beta_prime",
        parametersNames: ["alpha", "beta"],
        parametersValues: [5, 32],
        numberParameters: 2,
    },
    beta_prime_4p: {
        type: "continious",
        name: "Beta Prime 4P",
        id: "beta_prime_4p",
        parametersNames: ["alpha", "beta", "loc", "scale"],
        parametersValues: [5, 10, 20, 100],
        numberParameters: 4,
    },
    bradford: {
        type: "continious",
        name: "Bradford",
        id: "bradford",
        parametersNames: ["c", "min", "max"],
        parametersValues: [5, 20, 50],
        numberParameters: 3,
    },
    burr: {
        type: "continious",
        name: "Burr",
        id: "burr",
        parametersNames: ["A", "B", "C"],
        parametersValues: [2, 10, 0.5],
        numberParameters: 3,
    },
    burr_4p: {
        type: "continious",
        name: "Burr 4P",
        id: "burr_4p",
        parametersNames: ["A", "B", "C", "loc"],
        parametersValues: [10, 6, 5, 100],
        numberParameters: 4,
    },
    cauchy: {
        type: "continious",
        name: "Cauchy",
        id: "cauchy",
        parametersNames: ["x0", "gamma"],
        parametersValues: [5, 1],
        numberParameters: 2,
    },
    chi_square: {
        type: "continious",
        name: "Chi Square",
        id: "chi_square",
        parametersNames: ["df"],
        parametersValues: [7],
        numberParameters: 1,
    },
    chi_square_3p: {
        type: "continious",
        name: "Chi Square 3P",
        id: "chi_square_3p",
        parametersNames: ["df", "loc", "scale"],
        parametersValues: [5, 10, 2],
        numberParameters: 3,
    },
    dagum: {
        type: "continious",
        name: "Dagum",
        id: "dagum",
        parametersNames: ["a", "b", "p"],
        parametersValues: [5, 50, 3],
        numberParameters: 3,
    },
    dagum_4p: {
        type: "continious",
        name: "Dagum 4P",
        id: "dagum_4p",
        parametersNames: ["a", "b", "p", "loc"],
        parametersValues: [7, 2, 3, 100],
        numberParameters: 4,
    },
    erlang: {
        type: "continious",
        name: "Erlang",
        id: "erlang",
        parametersNames: ["k", "beta"],
        parametersValues: [50, 6],
        numberParameters: 2,
    },
    erlang_3p: {
        type: "continious",
        name: "Erlang 3P",
        id: "erlang_3p",
        parametersNames: ["k", "beta", "loc"],
        parametersValues: [50, 6, 1000],
        numberParameters: 3,
    },
    error_function: {
        type: "continious",
        name: "Error Function",
        id: "error_function",
        parametersNames: ["h"],
        parametersValues: [10],
        numberParameters: 1,
    },
    exponential: {
        type: "continious",
        name: "Exponential",
        id: "exponential",
        parametersNames: ["lambda"],
        parametersValues: [0.1],
        numberParameters: 1,
    },
    exponential_2p: {
        type: "continious",
        name: "Exponential 2P",
        id: "exponential_2p",
        parametersNames: ["lambda", "loc"],
        parametersValues: [0.1, 100],
        numberParameters: 2,
    },
    f: {
        type: "continious",
        name: "F",
        id: "f",
        parametersNames: ["df1", "df2"],
        parametersValues: [10, 30],
        numberParameters: 2,
    },
    f_4p: {
        type: "continious",
        name: "F 4P",
        id: "f_4p",
        parametersNames: ["df1", "df2", "loc", "scale"],
        parametersValues: [15, 9, 1000, 70],
        numberParameters: 4,
    },
    fatigue_life: {
        type: "continious",
        name: "Fatigue Life",
        id: "fatigue_life",
        parametersNames: ["gamma", "loc", "scale"],
        parametersValues: [0.5, 15, 10],
        numberParameters: 3,
    },
    folded_normal: {
        type: "continious",
        name: "Folded Normal",
        id: "folded_normal",
        parametersNames: ["miu", "sigma"],
        parametersValues: [100, 60],
        numberParameters: 2,
    },
    frechet: {
        type: "continious",
        name: "Frechet",
        id: "frechet",
        parametersNames: ["alpha", "loc", "scale"],
        parametersValues: [5, 10, 20],
        numberParameters: 3,
    },
    gamma: {
        type: "continious",
        name: "Gamma",
        id: "gamma",
        parametersNames: ["alpha", "beta"],
        parametersValues: [2, 10],
        numberParameters: 2,
    },
    gamma_3p: {
        type: "continious",
        name: "Gamma 3P",
        id: "gamma_3p",
        parametersNames: ["alpha", "beta", "loc"],
        parametersValues: [25, 2, 100],
        numberParameters: 3,
    },
    generalized_extreme_value: {
        type: "continious",
        name: "Generalized Extreme Value",
        id: "generalized_extreme_value",
        parametersNames: ["ξ", "miu", "sigma"],
        parametersValues: [0.1, 10, 2],
        numberParameters: 3,
    },
    generalized_gamma: {
        type: "continious",
        name: "Generalized Gamma",
        id: "generalized_gamma",
        parametersNames: ["a", "d", "p"],
        parametersValues: [10, 150, 20],
        numberParameters: 3,
    },
    generalized_gamma_4p: {
        type: "continious",
        name: "Generalized Gamma 4P",
        id: "generalized_gamma_4p",
        parametersNames: ["a", "d", "p", "loc"],
        parametersValues: [2, 6, 1, 30],
        numberParameters: 4,
    },
    generalized_logistic: {
        type: "continious",
        name: "Generalized Logistic",
        id: "generalized_logistic",
        parametersNames: ["c", "loc", "scale"],
        parametersValues: [3, 10, 5],
        numberParameters: 3,
    },
    generalized_normal: {
        type: "continious",
        name: "Generalized Normal",
        id: "generalized_normal",
        parametersNames: ["miu", "alpha", "beta"],
        parametersValues: [20, 3, 4],
        numberParameters: 3,
    },
    generalized_pareto: {
        type: "continious",
        name: "Generalized Pareto",
        id: "generalized_pareto",
        parametersNames: ["c", "miu", "sigma"],
        parametersValues: [-0.5, 10, 2],
        numberParameters: 3,
    },
    gibrat: {
        type: "continious",
        name: "Gibrat",
        id: "gibrat",
        parametersNames: ["loc", "scale"],
        parametersValues: [30, 100],
        numberParameters: 2,
    },
    gumbel_left: {
        type: "continious",
        name: "Gumbel Left",
        id: "gumbel_left",
        parametersNames: ["miu", "sigma"],
        parametersValues: [100, 30],
        numberParameters: 2,
    },
    gumbel_right: {
        type: "continious",
        name: "Gumbel Right",
        id: "gumbel_right",
        parametersNames: ["miu", "sigma"],
        parametersValues: [100, 60],
        numberParameters: 2,
    },
    half_normal: {
        type: "continious",
        name: "Half Normal",
        id: "half_normal",
        parametersNames: ["miu", "sigma"],
        parametersValues: [5, 2],
        numberParameters: 2,
    },
    hyperbolic_secant: {
        type: "continious",
        name: "Hyperbolic Secant",
        id: "hyperbolic_secant",
        parametersNames: ["miu", "sigma"],
        parametersValues: [1000, 200],
        numberParameters: 2,
    },
    inverse_gamma: {
        type: "continious",
        name: "Inverse Gamma",
        id: "inverse_gamma",
        parametersNames: ["alpha", "beta"],
        parametersValues: [5, 1],
        numberParameters: 2,
    },
    inverse_gamma_3p: {
        type: "continious",
        name: "Inverse Gamma 3P",
        id: "inverse_gamma_3p",
        parametersNames: ["alpha", "beta", "loc"],
        parametersValues: [30, 5, 100],
        numberParameters: 3,
    },
    inverse_gaussian: {
        type: "continious",
        name: "Inverse Gaussian",
        id: "inverse_gaussian",
        parametersNames: ["miu", "lambda"],
        parametersValues: [10, 20],
        numberParameters: 2,
    },
    inverse_gaussian_3p: {
        type: "continious",
        name: "Inverse Gaussian 3P",
        id: "inverse_gaussian_3p",
        parametersNames: ["miu", "lambda", "loc"],
        parametersValues: [10, 100, 60],
        numberParameters: 3,
    },
    johnson_sb: {
        type: "continious",
        name: "Johnson SB",
        id: "johnson_sb",
        parametersNames: ["xi", "lambda", "gamma", "delta"],
        parametersValues: [100, 1000, 5, 2],
        numberParameters: 4,
    },
    johnson_su: {
        type: "continious",
        name: "Johnson SU",
        id: "johnson_su",
        parametersNames: ["xi", "lambda", "gamma", "delta"],
        parametersValues: [200, 100, 6, 15],
        numberParameters: 4,
    },
    kumaraswamy: {
        type: "continious",
        name: "Kumaraswamy",
        id: "kumaraswamy",
        parametersNames: ["alpha", "beta", "min", "max"],
        parametersValues: [10, 30, 5, 20],
        numberParameters: 4,
    },
    laplace: {
        type: "continious",
        name: "Laplace",
        id: "laplace",
        parametersNames: ["miu", "b"],
        parametersValues: [17, 5],
        numberParameters: 2,
    },
    levy: {
        type: "continious",
        name: "Levy",
        id: "levy",
        parametersNames: ["miu", "c"],
        parametersValues: [2, 1],
        numberParameters: 2,
    },
    loggamma: {
        type: "continious",
        name: "Loggamma",
        id: "loggamma",
        parametersNames: ["c", "miu", "sigma"],
        parametersValues: [2, 10, 4],
        numberParameters: 2,
    },
    logistic: {
        type: "continious",
        name: "Logistic",
        id: "logistic",
        parametersNames: ["miu", "sigma"],
        parametersValues: [10, 5],
        numberParameters: 2,
    },
    loglogistic: {
        type: "continious",
        name: "Loglogistic",
        id: "loglogistic",
        parametersNames: ["alpha", "beta"],
        parametersValues: [5, 3],
        numberParameters: 2,
    },
    loglogistic_3p: {
        type: "continious",
        name: "Loglogistic 3P",
        id: "loglogistic_3p",
        parametersNames: ["alpha", "beta", "loc"],
        parametersValues: [5, 3, 100],
        numberParameters: 3,
    },
    lognormal: {
        type: "continious",
        name: "Lognormal",
        id: "lognormal",
        parametersNames: ["miu", "sigma"],
        parametersValues: [3, 0.3],
        numberParameters: 2,
    },
    maxwell: {
        type: "continious",
        name: "Maxwell",
        id: "maxwell",
        parametersNames: ["alpha", "loc"],
        parametersValues: [60, 100],
        numberParameters: 2,
    },
    moyal: {
        type: "continious",
        name: "Moyal",
        id: "moyal",
        parametersNames: ["miu", "sigma"],
        parametersValues: [20, 9],
        numberParameters: 2,
    },
    nakagami: {
        type: "continious",
        name: "Nakagami",
        id: "nakagami",
        parametersNames: ["m", "omega"],
        parametersValues: [12, 28],
        numberParameters: 2,
    },
    NON_CENTRAL_CHI_SQUARE: {
        type: "continious",
        name: "Non Central Chi Square",
        id: "NON_CENTRAL_CHI_SQUARE",
        parametersNames: ["lambda", "n"],
        parametersValues: [100, 5],
        numberParameters: 2,
    },
    non_central_f: {
        type: "continious",
        name: "Non Central F",
        id: "nc_f",
        parametersNames: ["lambda", "n1", "n2"],
        parametersValues: [200, 10, 500],
        numberParameters: 3,
    },
    non_central_t_student: {
        type: "continious",
        name: "Non Central T Student",
        id: "NON_CENTRAL_T_STUDENT",
        parametersNames: ["lambda", "n", "loc", "scale"],
        parametersValues: [3, 7, 500, 10],
        numberParameters: 4,
    },
    normal: {
        type: "continious",
        name: "Normal",
        id: "normal",
        parametersNames: ["miu", "sigma"],
        parametersValues: [5, 3],
        numberParameters: 2,
    },
    pareto_first_kind: {
        type: "continious",
        name: "Pareto First Kind",
        id: "pareto_first_kind",
        parametersNames: ["xm", "alpha", "loc"],
        parametersValues: [10, 5, 100],
        numberParameters: 3,
    },
    pareto_second_kind: {
        type: "continious",
        name: "Pareto Second Kind",
        id: "pareto_second_kind",
        parametersNames: ["xm", "alpha", "loc"],
        parametersValues: [23, 5, 100],
        numberParameters: 3,
    },
    pert: {
        type: "continious",
        name: "Pert",
        id: "pert",
        parametersNames: ["a", "b", "c"],
        parametersValues: [100, 500, 1000],
        numberParameters: 3,
    },
    power_function: {
        type: "continious",
        name: "Power Function",
        id: "power_function",
        parametersNames: ["alpha", "a", "b"],
        parametersValues: [10, 5, 100],
        numberParameters: 3,
    },
    rayleigh: {
        type: "continious",
        name: "Rayleigh",
        id: "rayleigh",
        parametersNames: ["gamma", "sigma"],
        parametersValues: [10, 2],
        numberParameters: 2,
    },
    reciprocal: {
        type: "continious",
        name: "Reciprocal",
        id: "reciprocal",
        parametersNames: ["a", "b"],
        parametersValues: [20, 100],
        numberParameters: 2,
    },
    rice: {
        type: "continious",
        name: "Rice",
        id: "rice",
        parametersNames: ["v", "sigma"],
        parametersValues: [5, 5],
        numberParameters: 2,
    },
    semicircular: {
        type: "continious",
        name: "Semicircular",
        id: "semicircular",
        parametersNames: ["loc", "R"],
        parametersValues: [20, 5],
        numberParameters: 2,
    },
    t_student: {
        type: "continious",
        name: "T Student",
        id: "t_student",
        parametersNames: ["df"],
        parametersValues: [10],
        numberParameters: 1,
    },
    t_student_3p: {
        type: "continious",
        name: "T Student 3P",
        id: "t_student_3p",
        parametersNames: ["df", "loc", "scale"],
        parametersValues: [24, 100, 3],
        numberParameters: 3,
    },
    trapezoidal: {
        type: "continious",
        name: "Trapezoidal",
        id: "trapezoidal",
        parametersNames: ["a", "b", "c", "d"],
        parametersValues: [100, 200, 700, 1000],
        numberParameters: 4,
    },
    triangular: {
        type: "continious",
        name: "Triangular",
        id: "triangular",
        parametersNames: ["a", "b", "c"],
        parametersValues: [100, 1000, 200],
        numberParameters: 3,
    },
    uniform: {
        type: "continious",
        name: "Uniform",
        id: "uniform",
        parametersNames: ["a", "b"],
        parametersValues: [50, 300],
        numberParameters: 2,
    },
    weibull: {
        type: "continious",
        name: "Weibull",
        id: "weibull",
        parametersNames: ["alpha", "beta"],
        parametersValues: [7, 10],
        numberParameters: 2,
    },
    weibull_3p: {
        type: "continious",
        name: "Weibull 3P",
        id: "weibull_3p",
        parametersNames: ["alpha", "beta", "loc"],
        parametersValues: [5, 3, 100],
        numberParameters: 3,
    },
};